### ISSUE TITLE
Adjust Makefile target 'install' for optional installation to the home folder

### ISSUE THREAD

**Issue by kiryph** [todotxt/todo.txt-cli#124] opened 2013-12-12 11:05 UTC
By default, make install will install all the files in /usr/local/bin. 

Can you make it possible to specify an installation prefix other than /usr/local, in particular $HOME?

Thank you

@ginatrapani sorry didn't see your wish to you use the mailing list instead of the issue tracker.

**Comment by karbassi** [comment] 2017-08-23 15:50
Duplicate of #221

**Closed by karbassi** 2017-08-23 15:50 UTC
