### ISSUE TITLE
Prioritizing multiple items at once does not match documentation

### ISSUE THREAD

**Issue by har96** [todotxt/todo.txt-cli#413] opened 2023-04-24 15:52 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
  
    $ todo.sh pri 1 a, 2 b, 3 c
    usage: todo.sh pri ITEM# PRIORITY[, ITEM# PRIORITY, ...]
    note: PRIORITY must be anywhere from A to Z.

**Which versions todo.sh are you using?**
> Run `todo.sh -V`

    TODO.TXT Command Line Interface v@DEV_VERSION@

    Homepage: http://todotxt.org
    Code repository: https://github.com/todotxt/todo.txt-cli/
    Contributors: https://github.com/todotxt/todo.txt-cli/graphs/contributors
    License: https://github.com/todotxt/todo.txt-cli/blob/master/LICENSE

**Which Operating System are you using?**
Ubuntu

**Which version of bash are you using?**
> Run `bash --version`

    zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Description

The documentation for the `pri` command does not match its behavior. Documentation leads you to believe that you should place commas between `<item> <priority>` pairs, when in reality the code fails if a comma is placed next to the priority. Without commas, the command works as expected:

    $ todo.sh pri 1 a 2 b 3 c

**Comment by inkarkat** [comment] 2023-04-24 16:35
Duplicate of #401. The confusing syntax affects almost all built-in commands, not just `pri`.

**Closed as completed by inkarkat** 2023-04-24 16:35 UTC
