### ISSUE TITLE
Add comments to a task (e.g., to remember the solution to a problem)

### ISSUE THREAD

**Issue by Nodragem** [todotxt/todo.txt-cli#189] opened 2016-09-17 10:59 UTC
Hi,

I always wanted to use todo.txt, but I finally keep using a normal text editor and/or markdown editor for many reasons. One of them is that I like to be able to comment on my tasks and on their resolution, so that I can access it later.

Do you think that such a feature would be of interest for many users?

**Comment by tivvit** [comment] 2016-09-17 21:06
+1

**Comment by mightyBroccoli** [comment] 2016-09-18 00:42
There are plugins coing just that out there, in fact even on the [wiki](https://github.com/ginatrapani/todo.txt-cli/wiki) in this repo.

Look [here](https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory), there is the official Addon List for todo-cli.
@Nodragem your specific Addon is https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#note--take-notes-related-to-tasks

**Comment by Nodragem** [comment] 2016-09-18 19:34
Yes that is true. However, as it is not part of the official todo.txt format, there is almost no GUI taking into account notes, I think.

**Comment by mightyBroccoli** [comment] 2016-09-19 08:51
@Nodragem I think that this script is not designed to be used in some form of GUI. Thats what the cli part of the name comes from. There are many GUIs and most of them are really good function wise and good looking too, but the main purpose is the usage inside the command line. 
Try QTodotxt they have multiple plugins supported and possibly they will adopt this problem or even have adopted it earlier. I dont have notes installed so I cant test.

**Comment by everyunitone** [comment] 2017-01-03 14:00
If #190 was implemented, it would likely assist with this use-case too (which I share). Albeit primarily for users of syntax-highlighted text editors, rather than the CLI users.

**Comment by PDiracDelta** [comment] 2017-06-05 13:21
+1 This would be one of two things that keep me from properly checking this tool out.
(the other being #205)

**Comment by zagortenay333** [comment] 2017-07-15 10:43
How are todo.txt clients supposed to handle the position of the comments though?

E.g., when you sort the tasks and need to write them to the todo.txt file. Or when you add a new task via a client.

**Comment by karbassi** [comment] 2017-08-23 04:00
Duplicate of todotxt/todotxt#1.

**Closed by karbassi** 2017-08-23 04:00 UTC
